language: csharp
sudo: required
solution: DevExpress.Xpo.ConsoleCoreDemo.sln
mono: none
dotnet: 2.1.0
dist: trusty
script:
 - cd XpoConsoleCoreDemo
 - dotnet restore
 - dotnet build -c Debug
 - cd ../XpoASPNETCoreDemo
 - dotnet restore
 - dotnet build -c Debug
 - cd ../XpoASPNETCoreMVCDemo
 - dotnet restore
 - dotnet build -c Debug 